name: bsforecast
channels:
  - conda-forge
dependencies:
  - python=3.11
  - numpy<2
  - pandas<=2.2.*
  - pip
  - matplotlib
  - pip:
      - tensorflow==2.12.*
      - yfinance
      - pytest
      - pytest-cov
      - black
      - isort
      - flake8
