name: bsforecast
channels:
  - conda-forge
dependencies:
  - python=3.11
  - numpy<2           
  - pandas
  - pip
  - matplotlib
  - pip:
      - tensorflow-macos==2.12.*
      - yahoofinancials
      - pytest
      - pytest-cov
      - black
      - isort
      - flake8
