name: bsforecast
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - numpy<2
  - pandas
  - scipy
  - matplotlib
  - pip
  - pytest
  - pytest-cov
  - protobuf<4
  - pip:
      - tensorflow==2.12.*
      - yahoofinancials
      - bayoo-docx
